/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myojektest.view;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import myojektest.model.Order;
import myojektest.controller.OrderController;
import java.awt.event.ActionListener;
import myojektest.model.Order;
import myojektest.controller.OrderController;
import myojektest.controller.FormOrderController;

/**
 *
 * @author sulto
 */
public class FormOrderView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormOrderView.class.getName());

    
    
    
    
    /**
     * Creates new form NewJFrame
     */
    public FormOrderView() {
        initComponents();
        //lblAdminVal.setText("Rp. " + OrderController.admin);
        
        Order orderModel = new Order();
        OrderController orderController = new OrderController();
        new FormOrderController(this, orderModel, orderController);
    }
    
    
    private String NoHP;
    
    public void setNoHP(String noHp){
       this.NoHP=noHp;
    }
    public String getNoHP(){
      return NoHP;
    }
    
    //untuk JarakChangeListener
    //getter
    public String getJarakInput() {
        return txtJarak.getText();
    }

    public String getAlamatDari() {
        return txtDari.getText();
    }
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    //setter
    public void setAdminLabelText(String text) {
        lblAdminVal.setText(text);
    }

    public void setBiayaValText(String text) {
        lblBiayaVal.setText(text);
    }

    public void setTotalValText(String text) {
        lblTotalVal.setText(text);
    }
    
    //untuk PesanListener
    public String getAlamatTujuan() {
        return txtTujuan.getText();
    }

    public String getSelectedTipe() {
        return (String) cmbTipe.getSelectedItem(); 
    }

    public void showSuccess(String message) {
        JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }

    public void showWarning(String message) {
        JOptionPane.showMessageDialog(this, message, "Peringatan", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJarak = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        txtJarak = new javax.swing.JTextField();
        lblTipe = new javax.swing.JLabel();
        cmbTipe = new javax.swing.JComboBox<>();
        lblBiaya = new javax.swing.JLabel();
        lblBiayaVal = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblDari = new javax.swing.JLabel();
        lblAdminVal = new javax.swing.JLabel();
        txtDari = new javax.swing.JTextField();
        sepTotal = new javax.swing.JSeparator();
        lblTujuan = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JTextField();
        lblTotalVal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJarak.setForeground(new java.awt.Color(102, 102, 102));
        lblJarak.setText("Jarak (km)");

        btnPesan.setBackground(new java.awt.Color(51, 102, 255));
        btnPesan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesan.setForeground(new java.awt.Color(255, 255, 255));
        btnPesan.setText("Pesan");
        btnPesan.setBorderPainted(false);
        btnPesan.addActionListener(this::btnPesanActionPerformed);

        txtJarak.setText("3.5");
        txtJarak.addActionListener(this::txtJarakActionPerformed);

        lblTipe.setForeground(new java.awt.Color(102, 102, 102));
        lblTipe.setText("Tipe");

        cmbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor", "Mobil" }));

        lblBiaya.setText("Biaya");

        lblBiayaVal.setText("Rp. 0");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Pesan");

        lblAdmin.setText("Admin");

        lblDari.setForeground(new java.awt.Color(102, 102, 102));
        lblDari.setText("Dari");

        lblAdminVal.setText("Rp. 2,000");

        txtDari.setText("Gerbang Utama, Fakultas Ilmu Komputer, M...");

        lblTujuan.setForeground(new java.awt.Color(102, 102, 102));
        lblTujuan.setText("Tujuan");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setText("Total");

        txtTujuan.setText("Kost Putra, Jalan Bunga Mawar, Kota Malang");

        lblTotalVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalVal.setText("Rp. 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepTotal)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDari)
                    .addComponent(txtTujuan)
                    .addComponent(txtJarak)
                    .addComponent(cmbTipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBiaya)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBiayaVal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAdminVal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalVal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDari)
                            .addComponent(lblTujuan)
                            .addComponent(lblJarak)
                            .addComponent(lblTipe))
                        .addGap(0, 306, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addComponent(lblDari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTujuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJarak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJarak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiaya)
                    .addComponent(lblBiayaVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmin)
                    .addComponent(lblAdminVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalVal))
                .addGap(20, 20, 20)
                .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJarakActionPerformed
//        // TODO add your handling code here:
//        String input = txtJarak.getText();
//        try {
//            int jarak = Integer.parseInt(input);
//            int harga = jarak * 5000;
//            lblBiayaVal.setText("Rp " + harga);
//            OrderController.setHarga(harga);
//
//            lblTotalVal.setText("Rp " + OrderController.total);
//
//        } catch (NumberFormatException e) {
//            lblBiayaVal.setText("Input tidak valid");
//        }
    }//GEN-LAST:event_txtJarakActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
//        // TODO add your handling code here:
//        try {
//            String asal = txtDari.getText();
//            String tujuan = txtTujuan.getText();
//            String jarakStr = txtJarak.getText();
//            
//            if (asal.isEmpty() || tujuan.isEmpty() || jarakStr.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Harap isi semua data!", "Peringatan", JOptionPane.WARNING_MESSAGE);
//                return;
//            }
//            
//            float jarak = Float.parseFloat(jarakStr);
//            int hargaDasar = (int) (jarak * 5000);
//            OrderController.setHarga(hargaDasar);
//            
//            Order orderBaru = new Order();
//            orderBaru.alamatJemput = asal;
//            orderBaru.alamatTujuan = tujuan;
//            orderBaru.jarak_km = jarak;
//            orderBaru.biaya = OrderController.total; 
//            orderBaru.tanggal = LocalDate.now().toString();
//            
//            orderBaru.passenger_id = 1;
//            orderBaru.driver_id = 1;
//
//            // 3. Kirim ke Controller
//            boolean sukses = OrderController.newOrder(orderBaru);
//
//            // 4. Tampilkan Alert Berhasil/Gagal
//            if (sukses) {
//                JOptionPane.showMessageDialog(this, "Order Berhasil Disubmit!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
//            } else {
//                JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke Database.", "Error", JOptionPane.ERROR_MESSAGE);
//            }
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Format Jarak harus angka!", "Error", JOptionPane.ERROR_MESSAGE);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_btnPesanActionPerformed

    public void addPesanListener(ActionListener listenForPesanButton) {
        btnPesan.addActionListener(listenForPesanButton);
    }
    
    public void addJarakChangeListener(ActionListener listenForJarakChange) {
        txtJarak.addActionListener(listenForJarakChange); 
    }
    
    public void addJarakDocumentListener(javax.swing.event.DocumentListener listenForJarakChange) {
        txtJarak.getDocument().addDocumentListener(listenForJarakChange);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormOrderView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesan;
    private javax.swing.JComboBox<String> cmbTipe;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdminVal;
    private javax.swing.JLabel lblBiaya;
    private javax.swing.JLabel lblBiayaVal;
    private javax.swing.JLabel lblDari;
    private javax.swing.JLabel lblJarak;
    private javax.swing.JLabel lblTipe;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalVal;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JSeparator sepTotal;
    private javax.swing.JTextField txtDari;
    private javax.swing.JTextField txtJarak;
    private javax.swing.JTextField txtTujuan;
    // End of variables declaration//GEN-END:variables
}
