/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myojektest.view;

import myojektest.model.OrderDAO;
import myojektest.model.DriverDAO;

import myojektest.model.Database;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import myojektest.controller.TakeOrderController;
import myojektest.model.Order;
import myojektest.model.PassengerDAO;

/**
 *
 * @author Muhammad Dzaky
 */
public class MainDriverView extends javax.swing.JFrame {

    /**
     * Creates new form DriverOrder
     */
    
    private OrderDAO orderDAO;
    private String nohp;
    private int driverid;
    private DriverDAO driverDAO;
    private PassengerDAO passengerDAO;
    TakeOrderController controllerTakeOrder = new TakeOrderController();
    
    public MainDriverView(OrderDAO orderDAO, String nohp,DriverDAO driverDAO,PassengerDAO passengerDAO) {
        initComponents();
        loadPesanan();
        this.nohp = nohp;
        this.orderDAO = orderDAO;
        BtnOrderan.setEnabled(false);
        this.driverDAO= driverDAO;
        driverid= driverDAO.getFiltered(null, nohp, null, null).getFirst().driver_id;
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PesananTabel = new javax.swing.JTable();
        Teks = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MyOjek = new javax.swing.JLabel();
        BtnOrderan = new javax.swing.JButton();
        riwayatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PesananTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Passanger", "Asal", "Tujuan", "Jarak", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PesananTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesananTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PesananTabel);

        Teks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Teks.setText("Siap untuk ambil orderan?");

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        MyOjek.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        MyOjek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MyOjek.setText("MyOjek");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MyOjek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(MyOjek)
                .addContainerGap())
        );

        BtnOrderan.setText("Ambil Orderan");
        BtnOrderan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderanActionPerformed(evt);
            }
        });

        riwayatButton.setText("Lihat Riwayat");
        riwayatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(Teks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnOrderan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(riwayatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Teks)
                .addGap(5, 5, 5)
                .addComponent(riwayatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnOrderan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOrderanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderanActionPerformed
        int row = PesananTabel.getSelectedRow();
        if (row == -1) return;
        int orderId = Integer.parseInt(PesananTabel.getValueAt(row, 0).toString());
        controllerTakeOrder.ambilOrderan(orderId, driverid);
        JOptionPane.showMessageDialog(this, "Order berhasil diambil!");
        loadPesanan();
    }//GEN-LAST:event_BtnOrderanActionPerformed

    private void PesananTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananTabelMouseClicked
        BtnOrderan.setEnabled(true);
    }//GEN-LAST:event_PesananTabelMouseClicked

    private void riwayatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatButtonActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {      
            new DriverHistoryView(orderDAO, nohp,driverDAO,passengerDAO).setVisible(true);
        });
    }//GEN-LAST:event_riwayatButtonActionPerformed

    
    public void loadPesanan(){
        DefaultTableModel model = (DefaultTableModel) PesananTabel.getModel();
        model.setRowCount(0);
        
        ArrayList<Order> list = controllerTakeOrder.loadPesanan();
        
        for (Order o : list) {
            model.addRow(new Object[]{
                o.order_id,
                o.passenger_id,
                o.getJemput(),
                o.getTujuan(),
                o.jarak_km,
                o.biaya
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDriverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDriverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDriverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDriverView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainDriverView(new OrderDAO(), ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOrderan;
    private javax.swing.JLabel MyOjek;
    private javax.swing.JTable PesananTabel;
    private javax.swing.JLabel Teks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton riwayatButton;
    // End of variables declaration//GEN-END:variables
}
